### ISSUE TITLE
Checking for disallowed theme names

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-check#106]
When themes are submitted with a name that is not allowed, we normally ask them to rename it and submit it again, but this can be prevented to some degree.

Examples:
Names containing "theme", "WordPress"
Names containing default themes, "TwentyFifteen Child" and so on.

**Comment by Otto42** [comment]
The uploader itself blocks the twenty-* names. Straight blocking this in theme-check could cause problems for any existing themes which pre-date this rule. Are there any such themes?

**Comment by carolinan** [comment]
I wasn't able to search trac for names containing different versions of "theme".  There are several tickets that are closed as not approved, and others that are renamed, but the original ticket is still open so that they can keep their place in the que.  I did not find any live themes using it, but my search query was incomplete.I tried using Summary.. contains...THEME: combined with theme, themes, _theme etc.

**Comment by carolinan** [comment]
OK actually this one is live: thememagic. https://themes.trac.wordpress.org/ticket/13982

**Comment by grappler** [comment]
We can make the theme as a special case so that it can bypass the theme check but I don't expect will get any updates for as it was last updated three years ago.

@Otto42 DO you need any help adding the [check](https://github.com/Otto42/theme-check/pull/109/files#diff-936a7b276e8e6904cd670ef7ed388bb7R1)?

**Comment by carolinan** [comment]
Surely there must be a better way to search for the names? The search I was able to do was incomplete, there might be more themes that are live.

**Comment by grappler** [comment]
Here is a list of all of the themes with the name "theme". There are 47. Nearly all of them have not been updated since 2011. Some have not author and have normally less then 100 installs. There is only one theme with the word WordPress that is "IPhone WordPress Theme"
![image](https://cloud.githubusercontent.com/assets/1785641/13979077/216521d6-f0d6-11e5-9142-8f3c66fa8f41.png)

**Comment by carolinan** [comment]
Would it be possible to allow it for updates but not for new themes?

**Comment by grappler** [comment]
We could theoretically create a whitelist in the code, if need be, like with the blacklist. I wonder if those themes without an author should be even live. @Otto42 may have some ideas.

**Comment by Otto42** [comment]
Patch seems reasonable. I'll take a look at it soon, tweak it a bit.

**Comment by carolinan** [comment]
Here is an example of a theme that passed the current check:
https://themes.trac.wordpress.org/ticket/80585

These 3 themes have been updated within the last 2 years:
ithemer, themelia, themesbydp
