### ISSUE TITLE
Don’t include admin/feature pointers [Required]

### ISSUE THREAD

**Issue by grappler** [WordPress/theme-check#126]
Check for `wp_enqueue_style( 'wp-pointer' ); wp_enqueue_script( 'wp-pointer' );`

**Comment by ahmadawais** [comment]
May I be bold enough to ask why is it wrong to use WP-Pointers in themes? They add value and make the user experience much better for beginners.

**Comment by grappler** [comment]
Sure, the wp core team asked the theme review team not to allow it as the API is not complete and not public. Anyone who uses it is using a workaround. WP Core cannot guarantee backward compatibility. The class `WP_Internal_Pointers` is also marked as final so that it cannot be extended.

**Comment by carolinan** [comment]
@grappler do you have any more context or information to share about the request from the core team?

Current usage is mainly in the Freemius framework and what I believe is a Redux framework "add-on".

I plan to close this issue as well as remove the requirement from the requirements page as part of the effort to reduce requirements.

**Comment by grappler** [comment]
@carolinan Sorry no, I think I did some research and found out this information. The request came in before my time. 

If plugin are allowed to use an incomplete API then I suppose Themes should be allowed to too. There does not seem to be any ticket to make the API Public in the future 🤷🏻

**Comment by SergeyBiryukov** [comment]
> May I be bold enough to ask why is it wrong to use WP-Pointers in themes? They add value and make the user experience much better for beginners.

It looks like the admin pointers API has not been used in [WordPress releases after version 4.1](https://core.trac.wordpress.org/browser/tags/5.7.2/src/wp-admin/includes/class-wp-internal-pointers.php#L149), with one exception in 4.9.6.

IIRC, it's because of various accessibility issues, and the API itself not being fully fledged. So it is my understanding that using the admin pointers is not exactly good practice and should probably be discouraged.

> I plan to close this issue as well as remove the requirement from the requirements page as part of the effort to reduce requirements.

I agree, if the goal is to simplify theme requirements and make them easier to support, I think this requirement is not strictly necessary. Even if the API is not recommended for use, it can still be allowed.

**Comment by carolinan** [comment]
Closing as wont fix based on the feedback received
