### ISSUE TITLE
Fatal error: Allowed memory exhausted

### ISSUE THREAD

**Issue by tsktech** [WordPress/theme-check#204]
many themes when check end up with error "Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 141901616 bytes) in /wordpress/wp-content/plugins/theme-check/main.php on line 30"

**Comment by jocastaneda** [comment]
What themes in particular do this? I've tried all the bundled themes going back to Twenty Ten and didn't encounter this.

**Comment by pattonwebz** [comment]
This seems to happen when the theme has a large `node_modules` directory inside of the theme. I am hesitant to exclude the folder from the checking as there are no themes live in the directory which have modules that exceed the limits of an average WP theme scan (the uploader check would fatal if there was).

**Comment by pattonwebz** [comment]
I opened PR #268 to add filters that can allow developers to skip over checking other files in a few directories while they are building the theme. These files would still be checked via the theme uploader on .org since the filters will not be in use there.

Skipping these files locally would reduce the chance of fatal errors due to memory exhaustion from scanning the contents of files in these directories.
