### ISSUE TITLE
Ignore build tools directories when performing the checks.

### ISSUE THREAD

**Issue by stefanobartoletti** [WordPress/theme-check#217]
I think it would be useful to ignore certain directories related to built tools when scanning theme files.

Some default ignores could be `node_modules`, `vendor`, `.git` and so on, but maybe also give the user the ability to manually select them.

**Comment by joyously** [comment]
Everything hosted in the repository must be checked.
Not everything from the source needs to be included in the final zip file, though. Evertyhing submitted must be reviewed.

**Comment by stefano-b** [comment]
These directories won't go in the repository, they are only used by local build tools like `npm`, `gulp`, `composer` and so on. They are used only during the development phase.

**Comment by joyously** [comment]
This plugin is the same code that is used for themes being uploaded to the repository. The folders in the theme folder being checked should match what will be uploaded.
In other words, you can't be testing correctly if your theme folder contains other files that won't be in the final zip.

**Comment by pattonwebz** [comment]
As per my comment in #204 I am hesitant to exclude these directories from the scan because if they are in the theme they should be checked at upload time. None of the themes in the directory currently have large enough dev directories to fatal the scanner or else the upload check would be throwing fatal errors and I have not heard any reports about that.

Perhaps one idea could be to add a filter flag that would allow a developer to exclude those directories during local development? What do you think of that idea?

**Comment by pattonwebz** [comment]
I opened PR #268 to add filters that can allow developers to skip over checking other files in a few directories while they are building the theme. These files would still be checked via the theme uploader on .org since the filters will not be in use there.

**Comment by stefano-b** [comment]
My idea was exactly to exclude folders used during development, that won't go in the package in any circumstance. Adding these filters seems a nice solution.
