### ISSUE TITLE
sanitize_callback is optional then why show REQUIRED.

### ISSUE THREAD

**Issue by ravikumarup** [WordPress/theme-check#277]
REQUIRED: Found a Customizer setting called 'theme_options_footer[footer_copyright]' in theme-functions.php that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.

**sanitize_callback is optional then why show REQUIRED.**

**Comment by pattonwebz** [comment]
@ravikumarup where have you seen that it is optional? You should always sanitize input.

**Comment by carolinan** [comment]
The confusion here is probably because the documentation for WP_Customize_Settings says that the sanitize_callback is optional.
https://developer.wordpress.org/reference/classes/wp_customize_setting/__construct/#parameters

@ravikumarup Theme Check is built for themes that you plan to submit to WordPress.org. And there themes are **required** to use the sanitize_callback.

Because of this I will close this issue.
